pip install Flask --upgrade
pip install Flask-Bootstrap --upgrade
pip install Flask-HTTPAuth --upgrade
pip install Flask-Login --upgrade
pip install Flask-Mail --upgrade
pip install Flask-Migrate --upgrade
pip install Flask-Moment --upgrade
pip install Flask-PageDown --upgrade
pip install Flask-SQLAlchemy --upgrade
pip install Flask-Script --upgrade
pip install Flask-WTF --upgrade
pip install Jinja2 --upgrade
pip install Mako --upgrade
pip install Markdown --upgrade
pip install MarkupSafe --upgrade
pip install SQLAlchemy --upgrade
pip install WTForms --upgrade
pip install Werkzeug --upgrade
pip install alembic --upgrade
pip install bleach --upgrade
pip install blinker --upgrade
pip install click --upgrade
pip install html5lib --upgrade
pip install itsdangerous --upgrade
pip install python-editor --upgrade
pip install six --upgrade
pip install ForgeryPy --upgrade
pip install Pygments --upgrade
pip install colorama --upgrade
pip install coverage --upgrade
pip install httpie --upgrade
pip install requests --upgrade
pip install selenium --upgrade