"""Added Modifier Text field to RandomTable and Public RandomTable

Revision ID: 1058cde5df9f
Revises: a92b3f3cd3e7
Create Date: 2020-07-05 14:49:25.030794

"""

# revision identifiers, used by Alembic.
revision = '1058cde5df9f'
down_revision = 'a92b3f3cd3e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifier_name', sa.Text(), nullable=True))

    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifier_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.drop_column('modifier_name')

    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.drop_column('modifier_name')

    # ### end Alembic commands ###
