"""Added RandomTable

Revision ID: 183d3f0348eb
Revises: 51f5ccfba190
Create Date: 2017-11-28 11:43:16.511000

"""

# revision identifiers, used by Alembic.
revision = '183d3f0348eb'
down_revision = '2356a38169ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_table',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('line_type', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'author_id')
    )
    op.create_index(op.f('ix_random_table_permissions'), 'random_table', ['permissions'], unique=False)
    op.create_index(op.f('ix_random_table_timestamp'), 'random_table', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_random_table_timestamp'), table_name='random_table')
    op.drop_index(op.f('ix_random_table_permissions'), table_name='random_table')
    op.drop_table('random_table')
    # ### end Alembic commands ###
