"""Add UserPublicContent, records what Public content user has selected

Revision ID: 329bbb5988b0
Revises: f5ede6741bff
Create Date: 2020-06-06 22:20:50.139706

"""

# revision identifiers, used by Alembic.
revision = '329bbb5988b0'
down_revision = 'f5ede6741bff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_public_content',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('announcement_id', 'author_id')
    )
    with op.batch_alter_table('user_public_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_public_content_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_public_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_public_content_timestamp'))

    op.drop_table('user_public_content')
    # ### end Alembic commands ###
