"""Added product_id and original_author_id fields

Revision ID: 3e41f05f6767
Revises: 8158848d45b8
Create Date: 2017-12-10 14:26:18.904000

"""

# revision identifiers, used by Alembic.
revision = '3e41f05f6767'
down_revision = '8158848d45b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macros', sa.Column('original_author_id', sa.Integer(), nullable=True))
    op.add_column('macros', sa.Column('product_id', sa.Text(), nullable=True))
    op.add_column('random_table', sa.Column('original_author_id', sa.Integer(), nullable=True))
    op.add_column('random_table', sa.Column('product_id', sa.Text(), nullable=True))
    op.add_column('set', sa.Column('original_author_id', sa.Integer(), nullable=True))
    op.add_column('set', sa.Column('product_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'product_id')
    op.drop_column('set', 'original_author_id')
    op.drop_column('random_table', 'product_id')
    op.drop_column('random_table', 'original_author_id')
    op.drop_column('macros', 'product_id')
    op.drop_column('macros', 'original_author_id')
    # ### end Alembic commands ###
