"""Simplify structure, change products into tags, rename ProductCategory to MarketCategory

Revision ID: 59f25294bdf9
Revises: ed294b771f42
Create Date: 2020-05-22 15:38:18.650323

"""

# revision identifiers, used by Alembic.
revision = '59f25294bdf9'
down_revision = 'ed294b771f42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.drop_column('product_id')

    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_marketplace_tags'), ['tags'], unique=False)
        batch_op.drop_index('ix_marketplace_product_id')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_random_table_tags'), ['tags'], unique=False)
        batch_op.drop_column('product_id')

    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_set_tags'), ['tags'], unique=False)
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_set_tags'))
        batch_op.drop_column('tags')

    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_random_table_tags'))
        batch_op.drop_column('tags')

    with op.batch_alter_table('marketplace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.TEXT(), nullable=True))
        batch_op.create_index('ix_marketplace_product_id', ['product_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_marketplace_tags'))
        batch_op.drop_column('tags')

    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
