"""Adding User Controls

Revision ID: 63c5fe144a13
Revises: 840486fe2851
Create Date: 2020-09-08 16:49:49.286078

"""

# revision identifiers, used by Alembic.
revision = '63c5fe144a13'
down_revision = '840486fe2851'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_ban', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('login_ban_description', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('login_ban_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('share_ban', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_ban_description', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('share_ban_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('share_ban_until')
        batch_op.drop_column('share_ban_description')
        batch_op.drop_column('share_ban')
        batch_op.drop_column('login_ban_until')
        batch_op.drop_column('login_ban_description')
        batch_op.drop_column('login_ban')

    # ### end Alembic commands ###
