"""Added Story Pin table

Revision ID: 66f24d5978fc
Revises: 753580d9e264
Create Date: 2020-05-18 16:47:37.261677

"""

# revision identifiers, used by Alembic.
revision = '66f24d5978fc'
down_revision = '753580d9e264'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_pins',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_pins')
    # ### end Alembic commands ###
