"""Added title to Story (Post)

Revision ID: 753580d9e264
Revises: 9519fc4e2106
Create Date: 2020-05-11 12:31:57.380723

"""

# revision identifiers, used by Alembic.
revision = '753580d9e264'
down_revision = '9519fc4e2106'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
