"""Add product table

Revision ID: 8158848d45b8
Revises: e77ae71bbc65
Create Date: 2017-12-08 20:15:04.614000

"""

# revision identifiers, used by Alembic.
revision = '8158848d45b8'
down_revision = 'e77ae71bbc65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tables', sa.Text(), nullable=True),
    sa.Column('macros', sa.Text(), nullable=True),
    sa.Column('sets', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'author_id')
    )
    op.create_index(op.f('ix_products_permissions'), 'products', ['permissions'], unique=False)
    op.create_index(op.f('ix_products_timestamp'), 'products', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_timestamp'), table_name='products')
    op.drop_index(op.f('ix_products_permissions'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
