"""Add SUPPORTING flag to tables, macros and collections

Revision ID: 840486fe2851
Revises: ea0bb459dec9
Create Date: 2020-07-28 10:14:39.818140

"""

# revision identifiers, used by Alembic.
revision = '840486fe2851'
down_revision = 'ea0bb459dec9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('public_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('public_macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('public_macros', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('public_collection', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    # ### end Alembic commands ###
