"""Add SUPPORTING flag to tables, macros and collections

Revision ID: 840486fe2851
Revises: ea0bb459dec9
Create Date: 2020-07-28 10:14:39.818140

"""

# revision identifiers, used by Alembic.
revision = '840486fe2851'
down_revision = 'ea0bb459dec9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comments_timestamp')

    op.drop_table('comments')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('public_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('public_macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('public_macros', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('public_collection', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('supporting')

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('disabled IN (0, 1)'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('ix_comments_timestamp', ['timestamp'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###
