"""Added product_id and original_author_id fields

Revision ID: 8c64f9ae87d3
Revises: 3e41f05f6767
Create Date: 2017-12-10 22:58:26.249000

"""

# revision identifiers, used by Alembic.
revision = '8c64f9ae87d3'
down_revision = '3e41f05f6767'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
