"""Added MarketPlace and ProductCategory tables

Revision ID: 9519fc4e2106
Revises: 8c64f9ae87d3
Create Date: 2017-12-21 16:47:05.069000

"""

# revision identifiers, used by Alembic.
revision = '9519fc4e2106'
down_revision = '8c64f9ae87d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('on_sale', sa.Boolean(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_product_id'), 'marketplace', ['product_id'], unique=False)
    op.create_index(op.f('ix_marketplace_timestamp'), 'marketplace', ['timestamp'], unique=False)
    op.create_table('product_category',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'product_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category')
    op.drop_index(op.f('ix_marketplace_timestamp'), table_name='marketplace')
    op.drop_index(op.f('ix_marketplace_product_id'), table_name='marketplace')
    op.drop_table('marketplace')
    # ### end Alembic commands ###
