"""Dropped parent field from collection

Revision ID: 9be558b8aa14
Revises: 663ba3ca5357
Create Date: 2020-05-26 13:58:01.371609

"""

# revision identifiers, used by Alembic.
revision = '9be558b8aa14'
down_revision = '663ba3ca5357'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('parent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
