"""Add announcement Id to linked tables

Revision ID: a92b3f3cd3e7
Revises: 329bbb5988b0
Create Date: 2020-06-17 13:07:13.255546

"""

# revision identifiers, used by Alembic.
revision = 'a92b3f3cd3e7'
down_revision = '329bbb5988b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_linked_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_linked_coll_announce_id', 'public_announcements', ['announcement_id'], ['id'])

    with op.batch_alter_table('public_linked_macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_linked_mac_announce_id', 'public_announcements', ['announcement_id'], ['id'])

    with op.batch_alter_table('public_linked_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_linked_tab_announce_id', 'public_announcements', ['announcement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_linked_tables', schema=None) as batch_op:
        batch_op.drop_constraint('fk_linked_coll_announce_id', type_='foreignkey')
        batch_op.drop_column('announcement_id')

    with op.batch_alter_table('public_linked_macros', schema=None) as batch_op:
        batch_op.drop_constraint('fk_linked_mac_announce_id', type_='foreignkey')
        batch_op.drop_column('announcement_id')

    with op.batch_alter_table('public_linked_collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_linked_tab_announce_id', type_='foreignkey')
        batch_op.drop_column('announcement_id')

    # ### end Alembic commands ###
