"""Added Macros table

Revision ID: b7ab14de6d0f
Revises: 183d3f0348eb
Create Date: 2017-11-28 11:54:23.897000

"""

# revision identifiers, used by Alembic.
revision = 'b7ab14de6d0f'
down_revision = '183d3f0348eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macros',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('definition_html', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'author_id')
    )
    op.create_index(op.f('ix_macros_permissions'), 'macros', ['permissions'], unique=False)
    op.create_index(op.f('ix_macros_timestamp'), 'macros', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macros_timestamp'), table_name='macros')
    op.drop_index(op.f('ix_macros_permissions'), table_name='macros')
    op.drop_table('macros')
    # ### end Alembic commands ###
