"""Added row count field to Tables

Revision ID: dfb242112911
Revises: 59f25294bdf9
Create Date: 2020-05-25 12:09:25.262736

"""

# revision identifiers, used by Alembic.
revision = 'dfb242112911'
down_revision = '59f25294bdf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_table', schema=None) as batch_op:
        batch_op.drop_column('row_count')

    # ### end Alembic commands ###
