"""Added Pins field to Story table

Revision ID: ed294b771f42
Revises: 66f24d5978fc
Create Date: 2020-05-19 09:57:03.496648

"""

# revision identifiers, used by Alembic.
revision = 'ed294b771f42'
down_revision = '66f24d5978fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('pins', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'pins')
    # ### end Alembic commands ###
