"""Added Set table

Revision ID: f017a3d88213
Revises: b7ab14de6d0f
Create Date: 2017-12-05 23:09:29.667000

"""

# revision identifiers, used by Alembic.
revision = 'f017a3d88213'
down_revision = 'b7ab14de6d0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'author_id')
    )
    op.create_index(op.f('ix_set_permissions'), 'set', ['permissions'], unique=False)
    op.create_index(op.f('ix_set_timestamp'), 'set', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_timestamp'), table_name='set')
    op.drop_index(op.f('ix_set_permissions'), table_name='set')
    op.drop_table('set')
    # ### end Alembic commands ###
