"""Add announcement_id to Public tables with ForeignKey constraint

Revision ID: f5ede6741bff
Revises: 66211fef0bb4
Create Date: 2020-06-06 11:31:36.050731

"""

# revision identifiers, used by Alembic.
revision = 'f5ede6741bff'
down_revision = '66211fef0bb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('col_announcement_fk1', 'public_announcements', ['announcement_id'], ['id'])

    with op.batch_alter_table('public_macros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('mac_announcement_fk1', 'public_announcements', ['announcement_id'], ['id'])

    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('tab_announcement_fk1', 'public_announcements', ['announcement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_random_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('announcement_id')

    with op.batch_alter_table('public_macros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('announcement_id')

    with op.batch_alter_table('public_collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('announcement_id')

    # ### end Alembic commands ###
